import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { ThemeProvider } from '@/components/theme-provider'
import { MenuNavigation } from '@/components/personal/navigationMenu'

const inter = Inter({ subsets: [ 'latin' ] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="pt-BR">
      <head>
        <meta property="og:title" content="Conheça a palavra de Deus" />
        <meta
          property="og:image"
          content={`${process.env.NEXT_PUBLIC_URL_BASE}og`}
        />
        <meta
          property="og:description"
          content="Um lugar para examinar a palavra do Senhor"
        />
      </head>
      <body className={inter.className}>
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <MenuNavigation />
          <div className="flex min-h-screen items-center justify-center">
            {children}
          </div>
        </ThemeProvider>
      </body>
    </html>
  )
}
